version: "3"
services:

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/logs:/logs"
      - "./mysql/my.cnf:/etc/my.cnf"
    ports:
      - "3306:3306"
    networks:
      - lnmp
            
  redis:
    image: redis:3.2
    container_name: redis
    volumes:
      - "./redis/conf/redis.conf:/etc/redis/redis.conf"
      - "./redis/data:/data"
      - "./redis/logs:/logs"
      - "./redis/cache:/redis_cache"
    ports:
      - "6379:6379"
    networks:
      - lnmp
            
  php-fpm:
    #image: php:7.0-fpm
    build: ./dir
    container_name: php-fpm
    working_dir: /www
    volumes:
      - "./www:/www"
      #- "./php/conf:/usr/local/etc/php"
    expose:
      - "9000"
    depends_on:
      - mysql
      - redis
    networks:
      - lnmp
      
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./www:/www"
      - "./nginx/logs:/var/log/nginx"
    ports:
      - "8088:80"
    depends_on:
      - php-fpm
      - mysql
      - redis
    networks:
      - lnmp
                    
networks:
  lnmp:
    driver: bridge
     